name: Lint and run tests

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: python -m pip install -e .[dev]
    - name: Run linter checks
      run: flake8 . && interrogate --verbose .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12' ]
        test-group: ['core', 'smartspim', 'mesoscope', 'utils']
        include:
          - test-group: 'core'
            dependencies: '[dev]'
            test-path: 'tests/core'
            test-pattern: 'test_*.py'
          - test-group: 'smartspim'
            dependencies: '[dev,smartspim]'
            test-path: 'tests/smartspim'
            test-pattern: 'test_*.py'
          - test-group: 'mesoscope'
            dependencies: '[dev,mesoscope]'
            test-path: 'tests/mesoscope'
            test-pattern: 'test_*.py'
          - test-group: 'bergamo'
            dependencies: '[dev,bergamo]'
            test-path: 'tests/bergamo'
            test-pattern: 'test_*.py'
          - test-group: 'utils'
            dependencies: '[dev,utils]'
            test-path: 'tests/utils'
            test-pattern: 'test_*.py'
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: python -m pip install -e .${{ matrix.dependencies }}
    - name: Run tests with coverage
      run: |
        coverage run --parallel-mode --source=src/aind_metadata_extractor -m unittest discover -s ${{ matrix.test-path }} -p ${{ matrix.test-pattern }}
    - name: Upload coverage data
      uses: actions/upload-artifact@v4
      with:
        name: coverage-data-py${{ matrix.python-version }}-${{ matrix.test-group }}
        path: .coverage.*
        include-hidden-files: true
        if-no-files-found: error

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: python -m pip install -e .[dev]
    - name: Download all coverage data
      uses: actions/download-artifact@v7
      with:
        pattern: coverage-data-py*
        merge-multiple: true
    - name: Combine coverage data
      run: |
        coverage combine
        coverage report
        coverage html
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: htmlcov/
